/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as ApiListsRouteImport } from './routes/api/lists'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiWordsRouteImport } from './routes/api/words'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists.index'
import { Route as AuthenticatedListsListIdRouteImport } from './routes/_authenticated/lists.$listId'
import { Route as ApiListsIdRouteImport } from './routes/api/lists.$id'
import { Route as ApiPublicListsRouteImport } from './routes/api/public/lists'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicWordsRouteImport } from './routes/api/public/words'
import { Route as ApiWordsIdRouteImport } from './routes/api/words.$id'
import { Route as ApiPublicListsIdRouteImport } from './routes/api/public/lists.$id'
import { Route as ApiPublicWordsIdRouteImport } from './routes/api/public/words.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiListsRoute = ApiListsRouteImport.update({
  id: '/api/lists',
  path: '/api/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordsRoute = ApiWordsRouteImport.update({
  id: '/api/words',
  path: '/api/words',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsListIdRoute =
  AuthenticatedListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiListsIdRoute = ApiListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiListsRoute,
} as any)
const ApiPublicListsRoute = ApiPublicListsRouteImport.update({
  id: '/api/public/lists',
  path: '/api/public/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWordsRoute = ApiPublicWordsRouteImport.update({
  id: '/api/public/words',
  path: '/api/public/words',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordsIdRoute = ApiWordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWordsRoute,
} as any)
const ApiPublicListsIdRoute = ApiPublicListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicListsRoute,
} as any)
const ApiPublicWordsIdRoute = ApiPublicWordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicWordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/search': typeof AuthenticatedSearchRoute
  '/api/lists': typeof ApiListsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/words': typeof ApiWordsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRoute
  '/api/lists/$id': typeof ApiListsIdRoute
  '/api/public/lists': typeof ApiPublicListsRouteWithChildren
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/words': typeof ApiPublicWordsRouteWithChildren
  '/api/words/$id': typeof ApiWordsIdRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
  '/api/public/lists/$id': typeof ApiPublicListsIdRoute
  '/api/public/words/$id': typeof ApiPublicWordsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/search': typeof AuthenticatedSearchRoute
  '/api/lists': typeof ApiListsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/words': typeof ApiWordsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/lists/$listId': typeof AuthenticatedListsListIdRoute
  '/api/lists/$id': typeof ApiListsIdRoute
  '/api/public/lists': typeof ApiPublicListsRouteWithChildren
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/words': typeof ApiPublicWordsRouteWithChildren
  '/api/words/$id': typeof ApiWordsIdRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/api/public/lists/$id': typeof ApiPublicListsIdRoute
  '/api/public/words/$id': typeof ApiPublicWordsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/api/lists': typeof ApiListsRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/api/words': typeof ApiWordsRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/lists/$listId': typeof AuthenticatedListsListIdRoute
  '/api/lists/$id': typeof ApiListsIdRoute
  '/api/public/lists': typeof ApiPublicListsRouteWithChildren
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/words': typeof ApiPublicWordsRouteWithChildren
  '/api/words/$id': typeof ApiWordsIdRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/api/public/lists/$id': typeof ApiPublicListsIdRoute
  '/api/public/words/$id': typeof ApiPublicWordsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/search'
    | '/api/lists'
    | '/api/mcp'
    | '/api/words'
    | '/.lovable/oauth/consent'
    | '/lists/$listId'
    | '/api/lists/$id'
    | '/api/public/lists'
    | '/api/public/mcp'
    | '/api/public/words'
    | '/api/words/$id'
    | '/lists/'
    | '/api/public/lists/$id'
    | '/api/public/words/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/search'
    | '/api/lists'
    | '/api/mcp'
    | '/api/words'
    | '/.lovable/oauth/consent'
    | '/lists/$listId'
    | '/api/lists/$id'
    | '/api/public/lists'
    | '/api/public/mcp'
    | '/api/public/words'
    | '/api/words/$id'
    | '/lists'
    | '/api/public/lists/$id'
    | '/api/public/words/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/search'
    | '/api/lists'
    | '/api/mcp'
    | '/api/words'
    | '/.lovable/oauth/consent'
    | '/_authenticated/lists/$listId'
    | '/api/lists/$id'
    | '/api/public/lists'
    | '/api/public/mcp'
    | '/api/public/words'
    | '/api/words/$id'
    | '/_authenticated/lists/'
    | '/api/public/lists/$id'
    | '/api/public/words/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiListsRoute: typeof ApiListsRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  ApiWordsRoute: typeof ApiWordsRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicListsRoute: typeof ApiPublicListsRouteWithChildren
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicWordsRoute: typeof ApiPublicWordsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/lists': {
      id: '/api/lists'
      path: '/api/lists'
      fullPath: '/api/lists'
      preLoaderRoute: typeof ApiListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/words': {
      id: '/api/words'
      path: '/api/words'
      fullPath: '/api/words'
      preLoaderRoute: typeof ApiWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$listId': {
      id: '/_authenticated/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthenticatedListsListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/lists/$id': {
      id: '/api/lists/$id'
      path: '/$id'
      fullPath: '/api/lists/$id'
      preLoaderRoute: typeof ApiListsIdRouteImport
      parentRoute: typeof ApiListsRoute
    }
    '/api/public/lists': {
      id: '/api/public/lists'
      path: '/api/public/lists'
      fullPath: '/api/public/lists'
      preLoaderRoute: typeof ApiPublicListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/words': {
      id: '/api/public/words'
      path: '/api/public/words'
      fullPath: '/api/public/words'
      preLoaderRoute: typeof ApiPublicWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/words/$id': {
      id: '/api/words/$id'
      path: '/$id'
      fullPath: '/api/words/$id'
      preLoaderRoute: typeof ApiWordsIdRouteImport
      parentRoute: typeof ApiWordsRoute
    }
    '/api/public/lists/$id': {
      id: '/api/public/lists/$id'
      path: '/$id'
      fullPath: '/api/public/lists/$id'
      preLoaderRoute: typeof ApiPublicListsIdRouteImport
      parentRoute: typeof ApiPublicListsRoute
    }
    '/api/public/words/$id': {
      id: '/api/public/words/$id'
      path: '/$id'
      fullPath: '/api/public/words/$id'
      preLoaderRoute: typeof ApiPublicWordsIdRouteImport
      parentRoute: typeof ApiPublicWordsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedListsListIdRoute: typeof AuthenticatedListsListIdRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedListsListIdRoute: AuthenticatedListsListIdRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiListsRouteChildren {
  ApiListsIdRoute: typeof ApiListsIdRoute
}

const ApiListsRouteChildren: ApiListsRouteChildren = {
  ApiListsIdRoute: ApiListsIdRoute,
}

const ApiListsRouteWithChildren = ApiListsRoute._addFileChildren(
  ApiListsRouteChildren,
)

interface ApiWordsRouteChildren {
  ApiWordsIdRoute: typeof ApiWordsIdRoute
}

const ApiWordsRouteChildren: ApiWordsRouteChildren = {
  ApiWordsIdRoute: ApiWordsIdRoute,
}

const ApiWordsRouteWithChildren = ApiWordsRoute._addFileChildren(
  ApiWordsRouteChildren,
)

interface ApiPublicListsRouteChildren {
  ApiPublicListsIdRoute: typeof ApiPublicListsIdRoute
}

const ApiPublicListsRouteChildren: ApiPublicListsRouteChildren = {
  ApiPublicListsIdRoute: ApiPublicListsIdRoute,
}

const ApiPublicListsRouteWithChildren = ApiPublicListsRoute._addFileChildren(
  ApiPublicListsRouteChildren,
)

interface ApiPublicWordsRouteChildren {
  ApiPublicWordsIdRoute: typeof ApiPublicWordsIdRoute
}

const ApiPublicWordsRouteChildren: ApiPublicWordsRouteChildren = {
  ApiPublicWordsIdRoute: ApiPublicWordsIdRoute,
}

const ApiPublicWordsRouteWithChildren = ApiPublicWordsRoute._addFileChildren(
  ApiPublicWordsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiListsRoute: ApiListsRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  ApiWordsRoute: ApiWordsRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicListsRoute: ApiPublicListsRouteWithChildren,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicWordsRoute: ApiPublicWordsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
